FUNC_PTR(0x4C4B20, GameActiveGameCommonDataIsServer,        BOOL (*)());
FUNC_PTR(0x4C4BA0, GameServerCodeLeave_Tracked,          SGameID (*)(BOOL bReturnToClient));
FUNC_PTR(0x4C4DF0, _GameServerCodeEnter,                    BOOL (*)());
FUNC_PTR(0x4C7CF0, GameIsStartUp,                           BOOL (*)());
FUNC_PTR(0x4C7D80, ServerIsLocal,                           BOOL (*)());
FUNC_PTR(0x7B2890, SGameGlobalsGet,                SGameGlobals* (*)());
FUNC_PTR(0x4C78D0, GameGetParts,                       GameParts (*)());
FUNC_PTR(0x9621D0, ServerGetOnlyGameConnection, GameConnectionID (*)());
FUNC_PTR(0x7B87D0, AppServerGetOnlyGame,                 SGameID (*)());
FUNC_PTR(0xC07700, bdLogSubscriber_publish,                 void (*)(const void *, const bdLogMessageType type, const bdNChar8 *const, const bdNChar8 *const file, const bdNChar8 *const, const bdUInt line, const bdNChar8 *const msg));
FUNC_PTR(0x758E40, CmdLineGetParams,              CmdLineParams* (*)());
FUNC_PTR(0x4C49D0, AppDrawFlagSet,                          void (*)(int32 nFlag, BOOL bValue));
FUNC_PTR(0xA27D30, XVarString_Set,                          bool (*)(XVarString *, const char *pszNewVal, uint32 uDirtyFlagsIfNecessary));
FUNC_PTR(0xA2C820, FileReadIntoMemory,                     void* (*)(FileReference *tFileRef, uint32 *dwSize, const ErrorCode eErrorCodeIfFails));
FUNC_PTR(0xA2CA50, FileReferenceInit,                       void (*)(FileReference *tFileRef, LPCSTR szPath));
FUNC_PTR(0xA2D030, FileCreate,                              BOOL (*)(FileReference *tFileRef));
FUNC_PTR(0xA2D0F0, FileExists,                              BOOL (*)(const FileReference *tFileRef));
FUNC_PTR(0xA2D100, FileOpen,                                BOOL (*)(FileReference *tFileRef, uint32 dwAccessFlags));
FUNC_PTR(0xA2D1D0, FileClose,                               void (*)(FileReference *tFileRef));
FUNC_PTR(0xA2D270, FileWrite,                               BOOL (*)(FileReference *tFileRef, const void *lpBuf, const uint32 dwOffset, const uint32 dwSize, ErrorCode eErrorCodeIfFails));
FUNC_PTR(0x0F2BB0, sReadFile,                               BOOL (*)(const char *szFileName, unsigned char **pData, uint32 *nDataSize));
FUNC_PTR(0xA2BF20, TraceInternal_Log,                       void (*)(const SeverityLevel eLevel, const uint32 dwFlags, const OutputStreamType eStream, LPCSTR szFormat, ...));
FUNC_PTR(0x0093D0, /*Blizz::Thread::*/ GetLocalStorage,    void* (*)(const Blizzard::Thread::TLSSlot *slot));
FUNC_PTR(0x719010, GetGameMessageTypeAndSize,               BOOL (*)(GameMessageType eMessageType, const XTypeDescriptor **pTypeDescriptor, uint32 *dwSize, const char **pszMessageLabel));
FUNC_PTR(0x1E0DF0, DisplaySeasonEndingMessage,              void (*)(int32 nMin));
FUNC_PTR(0x1E0F60, DisplayLongMessageForPlayer,             void (*)(const CRefString *sMessage, const Player *ptPlayer, const ImageTextureFrame *tImage, BOOL bUseLargeIcon));
FUNC_PTR(0x933EF0, DisplayGameMessageForAllPlayers,         void (*)(LPCSTR szStringDecoratedLabel, int nParam1, int nParam2));
FUNC_PTR(0x29B0E0, GfxWindowChangeDisplayMode,             void (*)(const DisplayMode *tMode));
FUNC_PTR(0x29CBB0, ImageTextureFrame_ctor,                  void (*)(ImageTextureFrame *, LPCSTR szDecoratedLabel));
FUNC_PTR(0x34C8D0, FormatTruncatedNumber,             CRefString (*)(float flValue, BOOL bUseMillions, BOOL bIncludeSpecialChar));
FUNC_PTR(0xA26F60, XVarBool_ToString,                blz::string (*)(uintptr_t * /* XVarBool *this */));
FUNC_PTR(0xA27360, XVarUint32_ToString,              blz::string (*)(uintptr_t * /* XVarUint32 *this */));
FUNC_PTR(0xA26EC0, XVarBool_Set,                            bool (*)(uintptr_t * /* XVarBool *this */, bool bNewVal, uint32 uDirtyFlagsIfNecessary));
FUNC_PTR(0xA272C0, XVarUint32_Set,                          bool (*)(uintptr_t * /* XVarUint32 *this */, uint32 uNewVal, uint32 uDirtyFlagsIfNecessary));
FUNC_PTR(0xA27A50, XVarFloat_Set,                           bool (*)(uintptr_t * /* XVarFloat *this */, float fNewVal, uint32 uDirtyFlagsIfNecessary));
FUNC_PTR(0x065270, OnSeasonsFileRetrieved,                  void (*)(void *, int32 eResult, std::shared_ptr<std::string> *pszFileData));
FUNC_PTR(0x066B10, StorageGetPublisherFile,          void (*)(int32 nUserIndex, const char *szFilename, Console::Online::StorageGetFileCallback pfnCallback));
// 185F70 d3boost::function_traits<void ()(Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&)>::result_type OnlineService::internal::call_callback<void ()(Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&),OnlineService::internal::function_bind_1_3<void,int,Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&,&(UIGameSettings::Console::`anonymous namespace'::sOnGetChallengeRiftData(int,Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&))>>(void *,d3boost::call_traits<d3boost::function_traits<void ()(Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&)>::arg1_type>::param_type,d3boost::call_traits<d3boost::function_traits<void ()(Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&)>::arg2_type>::param_type,d3boost::call_traits<d3boost::function_traits<void ()(Console::Online::StorageResult,D3::ChallengeRifts::ChallengeData const&,D3::Leaderboard::WeeklyChallengeData const&)>::arg3_type>::param_type):
// FUNC_PTR(0x185F70, OnChalRiftFileReceived,                  void (*)(Console::Online::StorageResult, D3::ChallengeRifts::ChallengeData const&, D3::Leaderboard::WeeklyChallengeData const&));
// FUNC_PTR(0x185F70, sOnGetChallengeRiftData,                 void (*)(int, Console::Online::StorageResult, D3::ChallengeRifts::ChallengeData /* const */ &, D3::Leaderboard::WeeklyChallengeData /* const */ &));
FUNC_PTR(0x185F70, sOnGetChallengeRiftData,                 void (*)(void *bind, Console::Online::StorageResult *param1, D3::ChallengeRifts::ChallengeData &param2, D3::Leaderboard::WeeklyChallengeData &param3));
// FUNC_PTR(0x185F70, sOnGetChallengeRiftData,                 void (*)(void *bind, Console::Online::StorageResult *param1, D3::ChallengeRifts::ChallengeData *param2, D3::Leaderboard::WeeklyChallengeData *param3));
FUNC_PTR(0xBB2B50, ParsePartialFromString,                  bool (*)(google::protobuf::MessageLite *, const blz::string *data));
FUNC_PTR(0x564C00, ChallengeData_ctor,                      void (*)(D3::ChallengeRifts::ChallengeData *));
// FUNC_PTR(0x564C00, CData_ctor,                              void (*)(uintptr_t *_this));
FUNC_PTR(0x62AAE0, WeeklyChallengeData_ctor,                void (*)(D3::Leaderboard::WeeklyChallengeData *));
FUNC_PTR(0x4C8B10, GameRandRangeInt,                       int32 (*)(const int32 nMin, const int32 nMax));

//
FUNC_PTR(0xB20, rawfree,                                    void (*)(void *));
FUNC_PTR(0xA36D20, SigmaMemoryNew,                         void* (*)(size_t size, size_t align, XMemoryAllocatorInterface *ptMemoryInterface, const BOOL fClear));
FUNC_PTR(0xA36E70, SigmaMemoryFree,                         void (*)(void *lp, XMemoryAllocatorInterface *ptMemoryInterface));
FUNC_PTR(0xA37020, SigmaMemoryMove,                         void (*)(void *lpDest, void *lpSrc, size_t size));
FUNC_PTR(0xA37080, op_delete_1,                             void (*)(void *));
FUNC_PTR(0xA370B0, op_delete_2,                             void (*)(void *));
FUNC_PTR(0x066690, blz_basic_string,                        void (*)(blz::string *, char const*, blz::allocator<char> const&));  //(const char *s, const blz::allocator<char> *alloc));
FUNC_PTR(0x066690, blz_string_ctor,                  blz::string (*)(char const*, blz::allocator<char> const&));           //(const char *s, const blz::allocator<char> *alloc));
FUNC_PTR(0x03C390, blz_make_stringf,                 blz::string (*)(char const* fmt,...));
FUNC_PTR(0x03C390, blz_make_stringfb,                blz::string (*)(void *,...));
// FUNC_PTR(0x03C390, blz_make_stringf,                 blz::string (*)(char const*,...));
