FUNC_PTR(0x505780, sGetItemTypeString,                CRefString (*)(GBID gbidItemType));
FUNC_PTR(0x69B230, AttribParamToString,               CRefString (*)(Attrib eAttrib, int32 nParam));
FUNC_PTR(0x69FBE0, FastAttribToString,                CRefString (*)(const FastAttribKey tKey));
FUNC_PTR(0x69B0D0, AttribStringToParam,                    int32 (*)(Attrib eAttrib, LPCSTR szParam));
FUNC_PTR(0x6CA3F0, GBIDToStringAll,                   CRefString (*)(const GBID *gbid));
FUNC_PTR(0x6CBC70, GBIDToString,                      CRefString (*)(GBID gbid, GameBalanceType eGBType, const BOOL fUsedForXMLFields));
FUNC_PTR(0x6F1480, StringListFetchLPCSTR,                 LPCSTR (*)(const SNO snoStringList, LPCSTR szLabel));

FUNC_PTR(0x483D70, ClearAssignedHero,                       void (*)(ActorCommonData *tACDItem));
FUNC_PTR(0x489210, ACDInventoryItemAllowedInSlot,      GameError (*)(const ActorCommonData *tACDItem, const InventoryLocation *tInvLoc, const BOOL fSkipRequirements, const BOOL fSwapping));
FUNC_PTR(0x48E910, ACDAddToInventory,                       void (*)(ActorCommonData *tACDItem, const InventoryLocation *tLocation, const BOOL bMarkItemAsDirty, InventorySlotType eCameFrom));
FUNC_PTR(0x490F20, SACDInventoryPickupOrSpillOntoGround,    BOOL (*)(ActorCommonData *tACDPlayer, ActorCommonData *tACDItem, const BOOL bTryStashFirst, ACDID *pidACDStackDest, const BOOL bAllowAutoEquip));
FUNC_PTR(0x4F44F0, ItemHasLabel,                            BOOL (*)(const GBID gbidItem, const ItemLabel eItemLabel));
FUNC_PTR(0x4FC120, SetBindingLevel,                         void (*)(ActorCommonData *tACD, int32_t eBindingType));
FUNC_PTR(0x4FC2E0, SetRecipient,                            void (*)(ActorCommonData *tACDItem, int32_t nPlayerIndex));
FUNC_PTR(0x4FF320, PopulateGenerator,                       void (*)(ActorCommonData *tACDItem, D3::Items::Generator *tGenerator, BOOL bSetRestoredBit));
FUNC_PTR(0x4FFF00, CItemGenerate,                          ACDID (*)(ACDNetworkName ann, D3::Items::Generator *tGenerator, ItemAffixFastAttribMap *arAffixSpecificAttributes));
FUNC_PTR(0x60CBC0, ItemsGenerator_ctor,                     void (*)(D3::Items::Generator *));
FUNC_PTR(0x60D250, ItemsGenerator_dtor,                     void (*)(D3::Items::Generator *));
FUNC_PTR(0x7A33A0, FlippyFindLandingLocation,               BOOL (*)(const ActorCommonData *tACDLaunching, const SNO snoActorFlippy, WorldPlace *tPlaceLanding, const Player *ptAssignedPlayer, const uintptr_t *pvBias, ACDID idACDKiller));
FUNC_PTR(0x7A4A00, FlippyDropCreateOnActor,                 void (*)(const ACDID idACDDropper, const ACDID idACDItem, const WorldPlace *tPlace));
FUNC_PTR(0x7DE1E0, SItemGenerate,                          ACDID (*)(const OnlineService::ItemId *tItemId, const D3::Items::Generator *tGenerator, const WorldPlace *tPlace, float flScale, uint32 tName));
FUNC_PTR(0x802700, AddItemToInventory,                      void (*)(Player *tPlayerFrom, D3::Items::Generator *tGenerator, BOOL bEquip));
FUNC_PTR(0x890A10, LootQuickCreateItem,                    ACDID (*)(const GBHandle *hGB, const BOOL fAutoIdentify));

FUNC_PTR(0x4B1690, GetCosmeticItemType,         CosmeticItemType (*)(GBID gbidItem));
FUNC_PTR(0x504BC0, ItemIsCosmeticItem,                      BOOL (*)(const GBID gbidItem));
FUNC_PTR(0x6A3D80, SetCraftLevel,                           void (*)(const CrafterType eType, Player *tPlayer, const int32 nLevel));
FUNC_PTR(0x6A4A20, Crafting_GetTransmogSlot,   InventorySlotType (*)(GBID gbidItem));
FUNC_PTR(0x7A1D80, ExperienceSetLevel,                      void (*)(const ACDID idACD, int32 nLevels, const BOOL fUpdateClient));
FUNC_PTR(0x7A1B00, ExperienceDropLootForAll,                void (*)(ActorCommonData *tACDLootee, ACDID idACDPrimaryLooter, uint32 dwGameEventNumber, BOOL fAutoIdentify, float flCameraBiasDist));
FUNC_PTR(0x7C2C50, SCosmeticItems_LearnCosmeticItem,        BOOL (*)(const ACDID idACDPlayer, const GBID gbidItem, CosmeticItemType eType, bool bPurchased));
FUNC_PTR(0x7C2F50, SCosmeticItems_LearnPet,                 BOOL (*)(const ACDID idACDPlayer, const GBID gbidItem, bool bPurchased));
FUNC_PTR(0x7E02B0, SItemPlayerExtractLegendaryPower,        BOOL (*)(Player *tPlayer, GBID gbidItem, GameError *eGameError));
FUNC_PTR(0x87FE40, SItemCrafting_TryUnlockTransmog,         BOOL (*)(GBID gbidTransmog, Player *tPlayer, BOOL bMustBeInInventory, BOOL bSendFullUpdate));
FUNC_PTR(0x880B40, SItemCrafting_TryUnlockSecondaryTmogs,   BOOL (*)(GBID gbidTransmog, Player *tPlayer));
FUNC_PTR(0x884930, SCrafterIncrementLevel,                  BOOL (*)(Player *tPlayer, CrafterType eType, uint32 nLevels));
FUNC_PTR(0x884A50, SItemCrafting_LearnRecipe,               void (*)(const ACDID idACDPlayer, const GBID gbidRecipe));
FUNC_PTR(0x886D70, sCrafterOnLevelUp,                       void (*)(const Player *tPlayer, CrafterType eType, const BOOL fChangedRank, const BOOL fSendToClient));
FUNC_PTR(0x88DDE0, LootRollForAncientLegendary,             void (*)(LootSpecifier *tSpecifier, const ACDID idACDLooter));
FUNC_PTR(0x4E5E50, GlobalSNOGet,                             SNO (*)(const SNO eGlobalSNO));
FUNC_PTR(0x6CB780, GBEnumerate,                             void (*)(GameBalanceType eType, GBHandleList *listResults));
FUNC_PTR(0x6CBCA0, GBGetHandlePool,                GBHandlePool* (*)());
FUNC_PTR(0x74A510, SNOToString,                       CRefString (*)(const SNOGroup snoGroup, const SNO snoHandle, const BOOL fUsedForXMLFields));
